import { formatCuisines, formatDistance } from "./formatters";
import type { Restaurant } from "./types";

export const TABLE_COLUMNS = [
  {
    key: 0,
    header: "ID",
    views: ["mobile", "tablet", "desktop"],
    value: (r: Restaurant) => r.id,
  },
  {
    key: 1,
    header: "Restaurant name",
    views: ["mobile", "tablet", "desktop"],
    value: (r: Restaurant) => r.name,
  },
  {
    key: 2,
    header: "Amenity",
    views: ["desktop"],
    value: (r: Restaurant) => r.amenity,
    width: 200,
  },
  {
    key: 3,
    header: "Cuisine",
    views: ["tablet", "desktop"],
    value: (r: Restaurant) => formatCuisines(r.cuisine),
    width: 250,
  },
  {
    key: 4,
    header: "Mi",
    views: ["mobile", "tablet", "desktop"],
    value: (r: Restaurant) => formatDistance(r.distanceMiles),
    width: 70,
  },
];

export const UI_CUISINES = {
  American: "american",
  Asian: "asian",
  Bagel: "bagel",
  Bakery: "bakery",
  "Bar and Grill": "bar_and_grill",
  Barbecue: "barbecue",
  Breakfast: "breakfast",
  British: "british",
  "Bubble Tea": "bubble_tea",
  Buffet: "buffet",
  Burger: "burger",
  Cajun: "cajun",
  "Chicken Fingers": "chicken_fingers",
  "Chicken Salad": "chicken_salad",
  Chicken: "chicken",
  Chinese: "chinese",
  "Coffee Shop": "coffee_shop",
  Cookies: "cookies",
  Dessert: "dessert",
  Donut: "donut",
  Ethiopian: "ethiopian",
  Fries: "fries",
  "Frozen Yogurt": "frozen_yogurt",
  Fusion: "fusion",
  Greek: "greek",
  "Hot Dog": "hot_dog",
  "Ice Cream": "ice_cream",
  Indian: "indian",
  International: "international",
  Italian: "italian",
  Japanese: "japanese",
  Juice: "juice",
  Korean: "korean",
  "Latin American": "latin_american",
  Maiz: "maiz",
  Mediterranean: "mediterranean",
  Mexican: "mexican",
  "Middle Eastern": "middle_eastern",
  Pancake: "pancake",
  Pasta: "pasta",
  Pizza: "pizza",
  Ramen: "ramen",
  Regional: "regional",
  Salad: "salad",
  Sandwich: "sandwich",
  Seafood: "seafood",
  Smoothie: "smoothie",
  Southern: "southern",
  "Steak House": "steak_house",
  Steak: "steak",
  Sushi: "sushi",
  Tamales: "tamales",
  "Tex-Mex": "tex-mex",
  Thai: "thai",
  Unknown: "unknown",
  Wings: "wings",
} as const;

export const API_CUISINES = {
  american: "American",
  asian: "Asian",
  bagel: "Bagel",
  bakery: "Bakery",
  bar_and_grill: "Bar and Grill",
  barbecue: "Barbecue",
  breakfast: "Breakfast",
  british: "British",
  bubble_tea: "Bubble Tea",
  buffet: "Buffet",
  burger: "Burger",
  cajun: "Cajun",
  chicken_fingers: "Chicken Fingers",
  chicken_salad: "Chicken Salad",
  chicken: "Chicken",
  chinese: "Chinese",
  coffee_shop: "Coffee Shop",
  cookies: "Cookies",
  dessert: "Dessert",
  donut: "Donut",
  ethiopian: "Ethiopian",
  fries: "Fries",
  frozen_yogurt: "Frozen Yogurt",
  fusion: "Fusion",
  greek: "Greek",
  hot_dog: "Hot Dog",
  ice_cream: "Ice Cream",
  indian: "Indian",
  international: "International",
  italian: "Italian",
  japanese: "Japanese",
  juice: "Juice",
  korean: "Korean",
  latin_american: "Latin American",
  maiz: "Maiz",
  mediterranean: "Mediterranean",
  mexican: "Mexican",
  middle_eastern: "Middle Eastern",
  pancake: "Pancake",
  pasta: "Pasta",
  pizza: "Pizza",
  ramen: "Ramen",
  regional: "Regional",
  salad: "Salad",
  sandwich: "Sandwich",
  seafood: "Seafood",
  smoothie: "Smoothie",
  southern: "Southern",
  steak_house: "Steak House",
  steak: "Steak",
  sushi: "Sushi",
  tamales: "Tamales",
  "tex-mex": "Tex-Mex",
  thai: "Thai",
  unknown: "Unknown",
  wings: "Wings",
} as const;
