import { formatCuisines, formatDistance } from "./formatters";
import type { APICuisine, CellAction, Restaurant, TableColumn } from "./types";

export const TABLE_COLUMNS: TableColumn[] = [
  {
    key: 0,
    header: "ID",
    views: ["mobile", "tablet", "desktop"],
    value: (r: Restaurant) => ({ text: r.id, type: "TEXT" }),
  },
  {
    key: 1,
    header: "Restaurant name",
    views: ["mobile", "tablet", "desktop"],
    value: (r: Restaurant, onClick?: CellAction) => {
      const c = (r.cuisines[0] as APICuisine) || "unknown";

      return {
        text: `${CUISINE_EMOJIS[c]} ${r.name}`,
        type: !r.googleMatch ? "TEXT" : "LINK",
        onClick,
      };
    },
  },
  {
    key: 2,
    header: "Amenity",
    views: ["desktop"],
    value: (r: Restaurant) => ({ text: r.amenity, type: "TEXT" }),
    width: 200,
  },
  {
    key: 3,
    header: "Cuisine",
    views: ["tablet", "desktop"],
    value: (r: Restaurant) => ({
      text: formatCuisines(r.cuisines),
      type: "TEXT",
    }),
    width: 250,
  },
  {
    key: 4,
    header: "Mi",
    views: ["mobile", "tablet", "desktop"],
    value: (r: Restaurant) => ({
      text: formatDistance(r.distanceMiles),
      type: "TEXT",
    }),
    width: 70,
  },
];

export const GROUPED_CUISINES = {
  American: [
    "american",
    "bar_and_grill",
    "barbecue",
    "burger",
    "cajun",
    "chicken",
    "chicken_fingers",
    "chicken_salad",
    "fries",
    "pizza",
    "hot_dog",
    "southern",
    "steak",
    "steak_house",
    "wings",
    "regional",
  ],
  "Latin American": ["mexican", "tex-mex", "latin_american", "tamales", "maiz"],
  Asian: ["asian", "chinese", "japanese", "sushi", "ramen", "korean", "thai"],
  European: [
    "italian",
    "pasta",
    "greek",
    "mediterranean",
    "british",
    "european",
  ],
  "Middle Eastern": ["middle_eastern", "indian", "ethiopian"],
  Breakfast: ["breakfast", "pancake", "bagel"],
  "Light Meals": ["sandwich", "salad"],
  Desserts: ["dessert", "ice_cream", "frozen_yogurt", "donut", "cookies"],
  "Cafes & Drinks": ["coffee_shop", "bubble_tea", "juice", "smoothie"],
  Seafood: ["seafood"],
  Other: ["fusion", "international", "buffet", "unknown", "bakery"],
};

export const API_CUISINES = {
  american: "American",
  asian: "Asian",
  bagel: "Bagel",
  bakery: "Bakery",
  bar_and_grill: "Bar and Grill",
  barbecue: "Barbecue",
  breakfast: "Breakfast",
  british: "British",
  bubble_tea: "Bubble Tea",
  buffet: "Buffet",
  burger: "Burger",
  cajun: "Cajun",
  chicken_fingers: "Chicken Fingers",
  chicken_salad: "Chicken Salad",
  chicken: "Chicken",
  chinese: "Chinese",
  coffee_shop: "Coffee Shop",
  cookies: "Cookies",
  dessert: "Dessert",
  donut: "Donut",
  ethiopian: "Ethiopian",
  european: "European",
  fries: "Fries",
  frozen_yogurt: "Frozen Yogurt",
  fusion: "Fusion",
  greek: "Greek",
  hot_dog: "Hot Dog",
  ice_cream: "Ice Cream",
  indian: "Indian",
  international: "International",
  italian: "Italian",
  japanese: "Japanese",
  juice: "Juice",
  korean: "Korean",
  latin_american: "Latin American",
  maiz: "Maiz",
  mediterranean: "Mediterranean",
  mexican: "Mexican",
  middle_eastern: "Middle Eastern",
  pancake: "Pancake",
  pasta: "Pasta",
  pizza: "Pizza",
  ramen: "Ramen",
  regional: "Regional",
  salad: "Salad",
  sandwich: "Sandwich",
  seafood: "Seafood",
  smoothie: "Smoothie",
  southern: "Southern",
  steak_house: "Steak House",
  steak: "Steak",
  sushi: "Sushi",
  tamales: "Tamales",
  "tex-mex": "Tex-Mex",
  thai: "Thai",
  unknown: "Unknown",
  wings: "Wings",
} as const;

export const CUISINE_EMOJIS: {
  [key in APICuisine]: string;
} = {
  american: "🍔",
  asian: "🍜",
  bagel: "🥯",
  bakery: "🥐",
  bar_and_grill: "🍻",
  barbecue: "🍖",
  breakfast: "🍳",
  british: "🥧",
  bubble_tea: "🧋",
  buffet: "🍽️",
  burger: "🍔",
  cajun: "🦐",
  chicken_fingers: "🍗",
  chicken_salad: "🥗",
  chicken: "🍗",
  chinese: "🥡",
  coffee_shop: "☕",
  cookies: "🍪",
  dessert: "🍰",
  donut: "🍩",
  ethiopian: "🍲",
  european: "🍝",
  fries: "🍟",
  frozen_yogurt: "🍦",
  fusion: "🍽️",
  greek: "🥙",
  hot_dog: "🌭",
  ice_cream: "🍨",
  indian: "🍛",
  international: "🌍",
  italian: "🍝",
  japanese: "🍣",
  juice: "🧃",
  korean: "🍲",
  latin_american: "🌮",
  maiz: "🌽",
  mediterranean: "🫒",
  mexican: "🌮",
  middle_eastern: "🧆",
  pancake: "🥞",
  pasta: "🍝",
  pizza: "🍕",
  ramen: "🍜",
  regional: "🍽️",
  salad: "🥗",
  sandwich: "🥪",
  seafood: "🦞",
  smoothie: "🥤",
  southern: "🍗",
  steak_house: "🥩",
  steak: "🥩",
  sushi: "🍣",
  tamales: "🫔",
  "tex-mex": "🌯",
  thai: "🍜",
  unknown: "🍽️",
  wings: "🍗",
};
